# fly.toml app configuration file generated for my-go-app on 2023-07-05T18:08:42+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "my-go-app"
primary_region = "atl"

[env]
  file = ".env"
  port = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
